<%@ Page Title="" Language="C#" MasterPageFile="~/Layout.Master" AutoEventWireup="true" CodeBehind="ManageRoles.aspx.cs" Inherits="HTW_Whisky.Roles.ManageRoles" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="phMain" runat="server">
    <b>Create a New Role: </b>
    <asp:TextBox ID="RoleName" runat="server"></asp:TextBox>
    <br />
    <asp:Button ID="CreateRoleButton" runat="server" Text="Create Role" 
        onclick="CreateRoleButton_Click" />
        <br />
        <br />
    <asp:GridView ID="RoleList" runat="server" 
        onselectedindexchanged="RoleList_SelectedIndexChanged" 
        AutoGenerateColumns="true" 
        AutoGenerateDeleteButton="true">
    </asp:GridView>  
    <asp:Label ID="Label1" runat="server" Text=""></asp:Label> 
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="phToolbar" runat="server">
</asp:Content>
